version: '3'

services:
  zookeeper2:
    image: wurstmeister/zookeeper
    ports:
      - 2182:2181
    restart: unless-stopped
  kafka2:
    image: wurstmeister/kafka
    ports:
      - 9093:9092
    volumes:
      - kafka2-data:/kafka/data
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.93:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper2:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    restart: unless-stopped
    depends_on:
      - zookeeper2
volumes: 
  kafka2-data:

