version: "3"

services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - 2181:2181
        restart: unless-stopped
    kafka:
        image: wurstmeister/kafka
        ports:
            - 9092:9092
        volumes:
            - kafka-data:/kafka/data
        environment:
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.98:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
        restart: unless-stopped
        depends_on:
            - zookeeper
volumes:
    kafka-data:
